### ISSUE TITLE
background

### ISSUE THREAD

**Issue by vincicat** [barcamphk/barcamphk2017#1]
You can try 
```css
.masthead {
    background: linear-gradient(to bottom, rgba(255,255,255,0.41) 0%,rgba(255,255,255,0.21) 100%) , transparent url(https://upload.wikimedia.org/wikipedia/commons/1/18/Hong_Kong_Night_Skyline.jpg) center scroll;
    background-size: cover;
}
```
if you need to fine tune the overlay you can use http://www.colorzilla.com/gradient-editor/
note: we have `autoprefixer` included in webpack
